= Using Micrometer Tracing Directly

* Goal
    ** how to use the Micrometer Tracing API -- to --
        *** create spans
        *** report spans

== Micrometer Tracing Examples

* basic operations | a span

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingApiTests.java[tags=manual_span_creation,indent=0]
-----

* how to continue a span | new thread ( ==  != thread / was started)

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingApiTests.java[tags=manual_span_continuation,indent=0]
-----

* if explicitly know who the parent span is -> how to create a child span

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingApiTests.java[tags=manual_span_joining,indent=0]
-----

== Micrometer Tracing Brave Setup

* set up Micrometer Tracing + Brave.
    ** _Example:_ how to create a Micrometer Tracing `Tracer` -- via -- Brave components / send completed spans to Zipkin:

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingApiTests.java[tags=brave_setup,indent=0]
-----

== Micrometer Tracing OpenTelemetry Setup

* set up Micrometer Tracing + OpenTelemetry (OTel).
    ** _Example:_ how to create a Micrometer Tracing `Tracer` -- via -- OTel components / send completed spans to Zipkin:

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingApiTests.java[tags=otel_setup,indent=0]
-----

== Micrometer Tracing Baggage API

* Traces connect application -- to -- application
    ** -- via -- header propagation
    ** passing along with the request
        *** trace identifiers
        *** `Baggage`
            **** == other properties
* _Example:_ how to create and extract baggage -- via -- Tracer API

[source,java,subs=+attributes]
-----
include::{include-bridges-java}/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/BraveTracingApiTests.java[tags=baggage_api,indent=0]
-----

* TODO: Check from here
IMPORTANT: For Brave, remember to set up the `PropagationFactory` so that it contains the baggage fields that you will be using in your code. Check the following example for details:

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingApiTests.java[tags=baggage_brave_setup,indent=0]
-----

=== Baggage with Micrometer Observation API

If you're using Micrometer Observation API, there's no notion of baggage. If you set up a `BaggageManager` to have the baggage fields configured, we will assume that when the Observation gets put in scope, whatever low and high cardinality keys are set on the Observation will be put in scope as baggage (assuming that their names match with the configuration on the `BaggageManager`). Below you can find example of such setup with OpenTelemetry `BaggageManager`.

[source,java,subs=+attributes]
-----
include::{include-bridges-java}/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/BaggageTests.java[tags=baggageManager,indent=0]

include::{include-bridges-java}/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/BaggageTests.java[tags=observationRegistrySetup,indent=0]

include::{include-bridges-java}/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/BaggageTests.java[tags=observation,indent=0]

include::{include-bridges-java}/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/BaggageTests.java[tags=observationScope,indent=0]
-----

== Aspect Oriented Programming

Micrometer Tracing contains `@NewSpan`, `@ContinueSpan`, and `@SpanTag` annotations that frameworks can use to create or customize spans for either specific types of methods such as those serving web request endpoints or, more generally, to all methods.

WARNING: Micrometer's Spring Boot configuration does _not_ recognize these aspects on arbitrary methods.

An AspectJ aspect is included. You can use it in your application, either through compile/load time AspectJ weaving or through framework facilities that interpret AspectJ aspects and proxy targeted methods in some other way, such as Spring AOP. Here is a sample Spring AOP configuration:

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingSpanAspectTests.java[tags=spring_config,indent=0]
-----

Applying `SpanAspect` makes `@NewSpan` and `@ContinueSpan` usable on any arbitrary method in an AspectJ proxied instance, as the following example shows:

[source,java,subs=+attributes]
-----
include::{include-java}/tracing/TracingSpanAspectTests.java[tags=example,indent=0]

// --------------------------
// ----- USAGE EXAMPLE ------
// --------------------------

include::{include-java}/tracing/TracingSpanAspectTests.java[tags=usage_example,indent=0]

-----

