:noheader:
[[tracing-documentation]]
= Tracing support

[[tracing-purpose]]
== Purpose

* problem of tracing
* approaches
    ** application developers have been creating the necessary tracing framework ðŸ‘ï¸	themselves ðŸ‘ï¸
    ** https://github.com/spring-cloud/spring-cloud-sleuth[Spring Cloud Sleuth]
        *** created in 2016, by the Spring Cloud team
        *** origin of Micrometer Tracing project
    ** Micrometer Tracing project
        *** Spring-agnostic
        *** == copy of Spring Cloud Sleuth
        *** 1.0.0 GA release in November 2022
        *** provides
            **** simple facade -- for the -- most popular tracer libraries (== NO vendor lock-in)
            **** -- tracing extension to -- Micrometer's `ObservationHandler`
                ***** Whenever an `Observation` is used -> a corresponding span is
                    ****** created,
                    ****** started,
                    ****** stopped
                    ****** reported
        *** design
            **** add little / -- NO overhead to your -- tracing collection activity
            **** maximize the portability


[[tracing-installing]]
== Installing

* via Bill of Materials (BOM)
    ** == project / contains ALL
    ** via
        *** Gradle

    implementation platform('io.micrometer:micrometer-tracing-bom:latest.release')
    implementation 'io.micrometer:micrometer-tracing'

        *** Maven

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-tracing-bom</artifactId>
                <version>${micrometer-tracing.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
          <groupId>io.micrometer</groupId>
          <artifactId>micrometer-tracing</artifactId>
        </dependency>
    </dependencies>

* recommendations
    ** add a tracing bridge
        *** -> `micrometer-tracing` library -- is added -- transitively
        *** __Example:__ `micrometer-tracing-bridge-brave` or `micrometer-tracing-bridge-otel`
    ** span exporters / reporters