= Supported Reporters, by Micrometer Tracing

* https://tanzu.vmware.com/observability[*Tanzu Observability by Wavefront*]
* https://zipkin.io[*OpenZipkin Zipkin*]

== Installing

* prerequisites
    ** xref:index.adoc[Micrometer Tracing BOM already added]
* via
    ** Gradle
        *** Tanzu Observability by Wavefront

            implementation 'io.micrometer:micrometer-tracing-reporter-wavefront'

        *** OpenZipkin Zipkin with Brave

            implementation 'io.zipkin.reporter2:zipkin-reporter-brave'

        *** OpenZipkin Zipkin with OpenTelemetry

            implementation 'io.opentelemetry:opentelemetry-exporter-zipkin'

        *** OpenZipkin URL sender dependency / -- send out spans, via a `URLConnectionSender`, to -- Zipkin

            implementation 'io.zipkin.reporter2:zipkin-sender-urlconnection'

    ** Maven
        *** Tanzu Observability by Wavefront

            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-tracing-reporter-wavefront</artifactId>
            </dependency>

        *** OpenZipkin Zipkin with Brave

            <dependency>
                <groupId>io.zipkin.reporter2</groupId>
                <artifactId>zipkin-reporter-brave</artifactId>
            </dependency>

        *** OpenZipkin Zipkin with OpenTelemetry

            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-exporter-zipkin</artifactId>
            </dependency>

        *** OpenZipkin URL sender dependency / -- send out spans, via a `URLConnectionSender`, to -- Zipkin

            <dependency>
                <groupId>io.zipkin.reporter2</groupId>
                <artifactId>zipkin-sender-urlconnection</artifactId>
            </dependency>

== Notes
* Brave, by default, adds Zipkin -- as a -- dependency
* If you want to use ONLY Wavefront & you use classpath dependent solutions ( _Example:_ Spring Boot) -> you need to exclude the transitive dependency | Zipkin / using Brave
    ** _Example:_ exlcuding the `io.zipkin.reporter2` group
